version: 2.1

jobs:
  lint:
    docker:
      - image: circleci/node:16.11.1
    steps:
      - checkout
      - run: npm install eslint
      - run: npm run lint
  install:
    docker:
      - image: circleci/node:16.11.1
    steps:
      - checkout
      - run: npm install
  test:
    docker:
      - image: circleci/node:16.11.1
    steps:
      - checkout
      - run: npm install
      - run: npm run test

jobs:
- install
- lint
- test