version: 2

jobs:
  build:
    docker:
      - image: circleci/node:16.11.1
    steps:
      - checkout
      - run: npm install
  lint:
    docker:
      - image: circleci/node:16.11.1
    steps:
      - checkout
      - run: npm install eslint
      - run: npm run lint
  test:
    docker:
      - image: circleci/node:16.11.1
    steps:
      - checkout
      - run: npm install
      - run: npm run test
  docker-build:
    machine: true
    steps:
      - checkout
      - run: make

workflows:
  version: 2
  pr-checks:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - lint
