version: 2

jobs:
  build:
    docker:
      - image: circleci/node:16.11.1
    steps:
      - checkout
      - run: npm install
  lint:
    docker:
      - image: circleci/node:16.11.1
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
  prettier:
    docker:
      - image: circleci/node:16.11.1
    steps:
      - checkout
      - run: npm install
      - run: npx prettier --check ./src
  test:
    docker:
      - image: circleci/node:16.11.1
    steps:
      - checkout
      - run: npm install
      - run: npm run test
  docker-build:
    machine: true
    steps:
      - checkout
      - run: make build

workflows:
  version: 2
  pr-checks:
    jobs:
      - build
      - lint:
          requires:
            - build
      - prettier:
          requires:
            - lint
      - test:
          requires:
            - prettier
      - docker-build:
          requires:
            - test
