version: 2

jobs:
  install:
    docker:
      - image: circleci/node:16.11.1
    steps:
      - checkout
      - run: npm install
  lint:
    docker:
      - image: circleci/node:16.11.1
    steps:
      - checkout
      - run: npm install eslint
      - run: npm run lint
  test:
    docker:
      - image: circleci/node:16.11.1
    steps:
      - checkout
      - run: npm install
      - run: npm run test

workflows:
  version: 2
  pr-checks: 
    jobs:
      - install
      - lint
      - test
