version: 2.1

jobs:
  install:
    docker:
      - image: circleci/node:16.11.1
    steps:
      - checkout
      - run: npm install
  lint:
    docker:
      - image: circleci/node:16.11.1
    steps:
      - checkout
      - run: npm install eslint
      - run: npm run lint
    requires:
      - install
  test:
    docker:
      - image: circleci/node:16.11.1
    steps:
      - checkout
      - run: npm install
      - run: npm run test
    requires:
      - install
      - test

workflows:
  build: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - install
      - lint
      - test
